version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
  app:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - POSTGRES_DB=db:5432/mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    container_name: app
    depends_on:
      - db
    ports:
      - "5000:5000"
volumes:
  mariadb-data:
