version: '3'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://myuser:mypassword@mariadb:3306/mydb
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
volumes:
  mariadb-data:
